version: "2"
services:
  factorio:
    image: factoriotools/factorio:2.0.32
    ports:
      - "34197:34197/udp"
      - "27015:27015/tcp"
    volumes:
      - ./factorio:/factorio
      - ./config:/factorio/config
    environment:
      - SERVER_NAME=NombreServer
      - SERVER_DESCRIPTION=Servidor Factorio sin DLCs ni mods
      - MAX_PLAYERS=5
      - SERVER_PASSWORD= contraseña # Cambia esto si quieres una contraseña
      - AUTOSAVE_INTERVAL=5
      - BIND=0.0.0.0
      - AUTOSAVE_SLOTS=3
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=admin123 # Cambia la contraseña de administrador
      - GENERATE_NEW_SAVE=true # Generar un nuevo mundo sin DLCs
      - LOAD_LATEST_SAVE=false # No cargar el mundo anterior
      - SAVE_NAME=mi_mundo # Nombre del archivo de guardado
      - VISIBILITY_PUBLIC=false # No público en Factorio Matching Server
      - VISIBILITY_LAN=true # Solo visible en LAN
      - DLC_SPACE_AGE=false # Desactivar DLC Space Age
      - MODS="" # No cargar mods
